name: .NET Core

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 2.2.207
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build with dotnet
      run: dotnet build websocket-sharper.sln --configuration Release
#    - name: Test with dotnet
#      run: dotnet test websocket-sharper.sln --configuration Release
